[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | env
  | _build
  | node_modules
  | assets
  | compose
  | requirements
  | staticfiles
)/
'''
